# Docker compose file for running a postgresql database

version: "3.1"

services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        env_file: .env_postgres
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
            - ../subject:/subject
